# Generated by Django 2.2 on 2021-11-11 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20211111_1741'),
        ('pedido', '0002_auto_20211111_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
    ]
