# Generated by Django 2.2 on 2021-11-11 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0005_auto_20211111_1756'),
        ('persona', '0003_auto_20211111_1741'),
        ('usuario', '0005_remove_usuario_producto'),
        ('pedido', '0004_remove_pedido_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comercio1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comercio.comercio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='persona1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
