# Generated by Django 2.2 on 2021-10-15 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
