# Generated by Django 2.2 on 2021-11-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20211111_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='producto',
        ),
    ]
