# Generated by Django 3.2.6 on 2021-10-15 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20211014_2239'),
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
    ]
