# Generated by Django 2.2 on 2021-11-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0004_auto_20211111_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercio',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='comercio',
            name='producto',
        ),
    ]
