# Generated by Django 3.2.6 on 2021-11-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0005_auto_20211111_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
