# Generated by Django 3.2.6 on 2021-10-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('origen', models.CharField(max_length=50)),
                ('peso', models.FloatField(blank=True, default=None, null=True)),
                ('volumen', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
