# Generated by Django 3.2.6 on 2021-10-15 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='peso',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='destino',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='estado',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='volumen',
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_alistamiento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_despacho',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_preparacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
