# Generated by Django 2.2 on 2021-11-11 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0005_auto_20211111_1756'),
        ('pedido', '0005_auto_20211111_1808'),
        ('producto', '0003_auto_20211111_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comercio1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comercio.comercio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedido'),
        ),
    ]
